concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "oc-dev"
  url = "http://localhost:90"
  token = "JvoAQ3XdigyMq2UHCPxW"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "python:2.7-alpine"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mode = "host"
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]